x-default-system-settings: &default-settings
  networks:
    - small_project_network
  restart: on-failure

services:
  postgres:
    <<: *default-settings
    container_name: postgres-18.1
    image: postgres:18.1-bookworm
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${SMPR_POSTGRES_USER}
      - POSTGRES_DB=${SMPR_POSTGRES_NAME}
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_password
    volumes:
      - postgres_data:/var/lib/postgresql
    secrets:
      - pg_password
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SMPR_POSTGRES_USER} -d ${SMPR_POSTGRES_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: small_project_db_data  

networks:
  small_project_network:
    name: small_project_network
    driver: bridge

secrets:
  pg_password:
    file: ./secrets/pg_password.txt
  