"""accounts_payments

Revision ID: d9aba8a34af7
Revises: 66d8c868509f
Create Date: 2026-07-08 13:02:07.487698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9aba8a34af7'
down_revision: Union[str, Sequence[str], None] = '66d8c868509f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата изменения'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Денежная единица'),
    sa.Column('balance', sa.BIGINT(), nullable=False, comment='Баланс в копейках'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('cash_accounts_user_id_idx', 'cash_accounts', ['user_id'], unique=False)
    op.create_table('cash_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание операции'),
    sa.Column('amount', sa.BigInteger(), nullable=False, comment='Сумма пополнения/списания в коп.'),
    sa.Column('account_rub_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_rub_id'], ['cash_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('cash_payments_account_rub_id_idx', 'cash_payments', ['account_rub_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('cash_payments_account_rub_id_idx', table_name='cash_payments')
    op.drop_table('cash_payments')
    op.drop_index('cash_accounts_user_id_idx', table_name='cash_accounts')
    op.drop_table('cash_accounts')
    # ### end Alembic commands ###
