"""black_tokens

Revision ID: 66d8c868509f
Revises: 61321c575748
Create Date: 2026-06-14 18:24:01.589410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66d8c868509f'
down_revision: Union[str, Sequence[str], None] = '61321c575748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('black_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False, comment='День создания'),
    sa.Column('jti', sa.UUID(), nullable=False, comment='Токен uuid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_black_tokens_jti'), 'black_tokens', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_black_tokens_jti'), table_name='black_tokens')
    op.drop_table('black_tokens')
    # ### end Alembic commands ###
