"""user

Revision ID: 61321c575748
Revises: 
Create Date: 2026-05-11 20:25:04.992156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61321c575748'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата изменения'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Пользователь'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Почта'),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Суперпользователь'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активен'),
    sa.Column('is_staff', sa.Boolean(), nullable=False, comment='Персонал'),
    sa.Column('first_name', sa.String(length=100), nullable=True, comment='Имя'),
    sa.Column('second_name', sa.String(length=100), nullable=True, comment='Фамилия'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='Отчество'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='user_email_key_uniq'),
    sa.UniqueConstraint('username', name='user_username_key_uniq')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
