"""cash_payment_transaction_id

Revision ID: fd31ff5010ec
Revises: d9aba8a34af7
Create Date: 2026-07-15 15:08:57.075257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd31ff5010ec'
down_revision: Union[str, Sequence[str], None] = 'd9aba8a34af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_payments', sa.Column('transaction_id', sa.UUID(), nullable=False, comment='код транзакции'))
    op.create_unique_constraint('cash_payments_transaction_id_uniq', 'cash_payments', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cash_payments_transaction_id_uniq', 'cash_payments', type_='unique')
    op.drop_column('cash_payments', 'transaction_id')
    # ### end Alembic commands ###
